### ISSUE TITLE
Crashing on put request to riak db

### ISSUE THREAD

**Issue by Scrib3r** [kostuyn/smart-proxy#4]
There is crashing if making put request to riak for creating new document.

```
HTTP PROXY PUT localhost:8098/riak/bonus_movements/cde385a7-2c9c-40bf-813e-549372896370?tr_cl=events.js-117-20&tr_sz=236
_http_outgoing.js:396
    throw new Error('Can\'t remove headers after they are sent.');
    ^

Error: Can't remove headers after they are sent.
    at ServerResponse.OutgoingMessage.removeHeader (_http_outgoing.js:396:11)
    at ServerResponse.send (/Users/nikita/Developer/smart-proxy/node_modules/express/lib/response.js:194:10)
    at IncomingMessage.<anonymous> (/Users/nikita/Developer/smart-proxy/handlers/proxy/index.js:113:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickCallback (node.js:425:17)
```

**Comment by kostuyn** [comment]
fixed it
